# Makefile for compiling in AppleTalk support in lpstyl.

# Change /usr/local/include to the directory containing the 'atalk' includes
# directory, and /usr/local/lib to the directory containing libatalk.a.

CFLAGS= -g -Wall -DATALK=1 -I${HOME}/usr/include -Dunix
LINKFLAGS= -L${HOME}/usr/lib -latalk

lpstyl: lpstyl.o adsp.o 
	${CC} ${CFLAGS} lpstyl.o adsp.o ${LINKFLAGS} -o lpstyl

